language: go
sudo: false
matrix:
  include:
  - go: 1.x
before_install:
- go get github.com/mitchellh/gox
install:
- 
script:
- go get -t -v ./...
- diff -u <(echo -n) <(gofmt -d .)
- go test -race
- gox -os="linux darwin windows" -arch="amd64" -output="aci-collector.{{.OS}}" -verbose ./...
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: AdUA5dI7XBvXVOkxvg8OWIAs/HYwERMMPW+Uaqc5QzkZs/j1aodxRMj5tQE3Pk5CiD3XY5KE120g1jIJo1IYJrqFPU0OxzrcUe9j01qTGYr5ckQPyc6pXt46hRGojfI+X4KucFoStMLaAdrBGDhzU+0HZSKYafsy5aRXdXm15RsJ+GMwa6WL5Lyd5d0bQVwUxtCa1cFHXp+KORZpatF2l4VF7a1OCjLEEEinKKZH3tn/W/Mv+oxmTJlC58u4wfKTeiUb/Pf94JJ8CsQFUA4Z4sj4ByUt3ylXaC31l2GWti/yt0YQAmP6Y4w8kY1j+wcAJG0KZT94PSHbU4Ou3a1uQqiNjLCReZUAsKUFVnkhVupXclxv6EafKZKAacmlXIaw0ss+U6ACs7nnpKvlrAl5Giw7dmjm1fWq3c80h1oFofnyRlixRFKXz7dHM6+YezOf2YHkNU8+LBGDf7WORh53tgRZ3xSEhGgp3rMASE+TbsYhUUcsjUISXX2YN1N43AvyOF9mcnGwKezDygwkz4JaVB+I6w5zrPUKKXPGxlMazUSzTtRyUGRiFYEsifOmJepAlqNuawXwX/QNa26BuHoXiG3aU4mSgPwm449G8kEjwGe5HC8oOtzZ6P7lfR5YcYShnHXkpkMdvCLeRszXedoqhg1jMzAc60pOv1BXgHVQklQ=
  file:
    aci-collector.windows.exe
    aci-collector.darwin
    aci-collector.linux
  on:
    repo: brightpuddle/aci-health-check-collector
    tags: true
